Restaurant
mkhajure7000/online_food_delivery_application pull request #3
Opened 2022-08-24 10:41 UTC by mkhajure7000

2022-08-24 11:17 UTC, Shubham-Porwall commented on app/controllers/restaurants_controller.rb
> +  before_action :require_restaurant, only: [:update, :edit,:destroy]
use %i

2022-08-24 11:17 UTC, Shubham-Porwall commented on app/controllers/restaurants_controller.rb
> +    @restaurant = current_user.restaurants.find(params[:id])
handle negative scenarios

2022-08-24 11:17 UTC, Shubham-Porwall commented on test/fixtures/restaurants.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
remove unnecessary files

2022-08-25 05:46 UTC, Shubham-Porwall commented on app/controllers/restaurants_controller.rb
> +    @restaurant = current_user.restaurants.find(params[:id])
^^

2022-08-25 13:58 UTC, Shubham-Porwall commented on app/controllers/restaurants_controller.rb
> +    if @restaurant.nil?
You can handle this condition in filter so it will help's for all three actions !

2022-08-26 08:08 UTC, Shubham-Porwall approved these changes
Looks Good to me !

2022-08-26 09:29 UTC, kalpana19sharma requested changes

2022-08-26 09:29 UTC, kalpana19sharma commented on app/controllers/restaurants_controller.rb
> +  def require_restaurant
Rename this method

2022-08-26 09:29 UTC, kalpana19sharma commented on app/controllers/restaurants_controller.rb
> +    if @restaurant.nil?
prefer using `.present?` or `.blank?`

2022-08-26 09:29 UTC, kalpana19sharma commented on app/views/restaurants/_form.html.erb
> +      </div>
Extract the error rendering logic in a shared partial. I think we have same logic for users views as well.

2022-08-26 09:29 UTC, kalpana19sharma commented on app/views/restaurants/_form.html.erb
> +      <%= form.text_field :address, class: "form-control"%>
Fix spaces

2022-08-26 09:29 UTC, kalpana19sharma commented on app/views/restaurants/edit.html.erb
> +<%=render "form", restaurant: @restaurant %>
Fix spaces

2022-08-26 09:29 UTC, kalpana19sharma commented on app/views/restaurants/index.html.erb
> +<h1><%= button_to "logout", {:controller => :sessions, :action => 'destroy', :id => current_user.id }, :method => :delete, class: "btn btn-success"%></h1>
Don't use arrow syntax

2022-08-26 09:29 UTC, kalpana19sharma commented on app/views/restaurants/index.html.erb
> +      <img class="card-img-top" src="#" alt="Card image cap" height="200" width="200" style="border-radius:.60rem;">
don't use inline css

2022-08-26 09:29 UTC, kalpana19sharma commented on app/views/users/index.html.erb
> +  <h1><%= button_to "logout", {:controller => :sessions, :action => 'destroy', :id => current_user.id }, :method => :delete, class: "btn btn-success"%></h1>
Don't use arrow syntax

2022-08-26 09:29 UTC, kalpana19sharma commented on app/views/users/index.html.erb
> +  <h1><%= button_to "logout", {:controller => :sessions, :action => 'destroy', :id => current_user.id }, :method => :delete, class: "btn btn-success"%></h1>
And fix spaces

2022-08-26 09:29 UTC, kalpana19sharma commented on config/routes.rb
> +  resources :restaurants
are you using show action?

2022-08-31 07:37 UTC, merged